server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: pass1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: TESTING-SERVICE