server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alphadb
    username: root
    password: password1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  application:
    name: TESTING-SERVICE
